Home task 3
oksanazah/courses-app-react pull request #5
Opened 2023-03-25 18:42 UTC by oksanazah

2023-03-27 15:39 UTC, KitTheProgrammer requested changes
No bugs, good job)

2023-03-27 15:39 UTC, KitTheProgrammer commented on src/App.tsx
> +const store = createStore(rootReducer, composeWithDevTools());
this line should be in `src/store/index.ts`

2023-03-27 15:39 UTC, KitTheProgrammer commented on src/App.tsx
> +	const userName: User = useSelector(selectUser);
I think type inferring can be applied here if you configured your selector correctly

2023-03-27 15:39 UTC, KitTheProgrammer commented on src/App.tsx
> +	}, [dispatch]);
It's not that important, but callback inside the useEffect can be async
`useEffect(async () => {})`

2023-03-27 15:39 UTC, KitTheProgrammer commented on src/components/CourseInfo/CourseInfo.tsx
> +	}, [courseId]);
using async here will be beneficial

2023-03-27 15:39 UTC, KitTheProgrammer commented on src/components/Header/Header.tsx
>  		localStorage.removeItem('name');
You can remove items from local storage from your `onLogout` action

2023-03-27 15:39 UTC, KitTheProgrammer commented on src/components/Login/Login.tsx
> +		localStorage.setItem('name', `${result.payload?.user?.name}`);
local storage operations can be moved to your `onLogin` action

2023-03-27 15:39 UTC, KitTheProgrammer commented on src/helpers/selectors.tsx
this file have to be in `src/store` or `src/store/selectors`

2023-03-27 15:39 UTC, KitTheProgrammer commented on src/services.tsx
> +};
can't see any error handling here.

if you have it at places you are using these functions then it is better to move them here

2023-03-27 15:39 UTC, KitTheProgrammer commented on src/store/authors/actionCreators.tsx
> +};
no error handling

2023-03-27 15:39 UTC, KitTheProgrammer commented on src/store/courses/actionCreators.tsx
> +};
no error handling

2023-03-28 16:00 UTC, EpamFanAnton approved these changes
good job 15

2023-03-28 16:02 UTC, merged